"""init_card_key_system

Revision ID: 36e64d566b69
Revises: 
Create Date: 2026-05-12 21:35:30.838592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e64d566b69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('card_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_key', sa.String(length=64), nullable=False),
    sa.Column('access_link', sa.String(length=255), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_link')
    )
    op.create_index(op.f('ix_card_keys_card_key'), 'card_keys', ['card_key'], unique=True)
    op.create_table('daily_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_key_id', sa.Uuid(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('rewrite_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_key_id'], ['card_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_key_id', 'usage_date')
    )
    op.create_index(op.f('ix_daily_usage_card_key_id'), 'daily_usage', ['card_key_id'], unique=False)
    op.create_table('rewrite_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_key_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_key_id'], ['card_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewrite_jobs_card_key_id'), 'rewrite_jobs', ['card_key_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rewrite_jobs_card_key_id'), table_name='rewrite_jobs')
    op.drop_table('rewrite_jobs')
    op.drop_index(op.f('ix_daily_usage_card_key_id'), table_name='daily_usage')
    op.drop_table('daily_usage')
    op.drop_index(op.f('ix_card_keys_card_key'), table_name='card_keys')
    op.drop_table('card_keys')
    op.drop_table('admins')
    # ### end Alembic commands ###
